// Copyright 2014, Hǎiliàng Wáng. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package sdl

const (
	KScancodeMask                           = (1 << 30)
	AlphaOpaque                             = 255
	AlphaTransparent                        = 0
	AssemblyRoutines                        = 1
	AssertLevel                             = 2
	AudioAllowAnyChange                     = (AudioAllowFrequencyChange | AudioAllowFormatChange | AudioAllowChannelsChange)
	AudioAllowChannelsChange                = 0x00000004
	AudioAllowFormatChange                  = 0x00000002
	AudioAllowFrequencyChange               = 0x00000001
	AudioDriverAlsa                         = 1
	AudioDriverAlsaDynamic                  = "Libasound.So.2"
	AudioDriverDisk                         = 1
	AudioDriverDummy                        = 1
	AudioDriverOss                          = 1
	AudioMaskBitsize                        = (0xFF)
	AudioMaskDatatype                       = (1 << 8)
	AudioMaskEndian                         = (1 << 12)
	AudioMaskSigned                         = (1 << 15)
	BigEndian                               = 4321
	ButtonLeft                              = 1
	ButtonLmask                             = (ButtonLeft)
	ButtonMiddle                            = 2
	ButtonMmask                             = (ButtonMiddle)
	ButtonRight                             = 3
	ButtonRmask                             = (ButtonRight)
	ButtonX1                                = 4
	ButtonX1mask                            = (ButtonX1)
	ButtonX2                                = 5
	ButtonX2mask                            = (ButtonX2)
	CachelineSize                           = 128
	Disable                                 = 0
	Dontfree                                = 0x00000004
	Enable                                  = 1
	FilesystemUnix                          = 1
	HapticAutocenter                        = (1 << 13)
	HapticCartesian                         = 1
	HapticConstant_                         = (1 << 0)
	HapticCustom_                           = (1 << 11)
	HapticDamper                            = (1 << 8)
	HapticFriction                          = (1 << 10)
	HapticGain                              = (1 << 12)
	HapticInertia                           = (1 << 9)
	HapticInfinity                          = 4294967295
	HapticLeftright                         = (1 << 2)
	HapticLinux                             = 1
	HapticPause_                            = (1 << 15)
	HapticPolar                             = 0
	HapticRamp_                             = (1 << 6)
	HapticSawtoothdown                      = (1 << 5)
	HapticSawtoothup                        = (1 << 4)
	HapticSine                              = (1 << 1)
	HapticSpherical                         = 2
	HapticSpring                            = (1 << 7)
	HapticStatus                            = (1 << 14)
	HapticTriangle                          = (1 << 3)
	HatCentered                             = 0x00
	HatDown                                 = 0x04
	HatLeft                                 = 0x08
	HatLeftdown                             = (HatLeft | HatDown)
	HatLeftup                               = (HatLeft | HatUp)
	HatRight                                = 0x02
	HatRightdown                            = (HatRight | HatDown)
	HatRightup                              = (HatRight | HatUp)
	HatUp                                   = 0x01
	HintAllowTopmost                        = "AllowTopmost"
	HintFramebufferAcceleration             = "FramebufferAcceleration"
	HintGamecontrollerconfig                = "Gamecontrollerconfig"
	HintGrabKeyboard                        = "GrabKeyboard"
	HintIdleTimerDisabled                   = "IosIdleTimerDisabled"
	HintJoystickAllowBackgroundEvents       = "JoystickAllowBackgroundEvents"
	HintOrientations                        = "IosOrientations"
	HintRenderDirect3dThreadsafe            = "RenderDirect3dThreadsafe"
	HintRenderDriver                        = "RenderDriver"
	HintRenderOpenglShaders                 = "RenderOpenglShaders"
	HintRenderScaleQuality                  = "RenderScaleQuality"
	HintRenderVsync                         = "RenderVsync"
	HintTimerResolution                     = "TimerResolution"
	HintVideoHighdpiDisabled                = "VideoHighdpiDisabled"
	HintVideoMinimizeOnFocusLoss            = "VideoMinimizeOnFocusLoss"
	HintVideoX11Xinerama                    = "VideoX11Xinerama"
	HintVideoX11Xrandr                      = "VideoX11Xrandr"
	HintVideoX11Xvidmode                    = "VideoX11Xvidmode"
	HintXinputEnabled                       = "XinputEnabled"
	IconvE2big                              = -2
	IconvEilseq                             = -3
	IconvEinval                             = -4
	IconvError                              = -1
	Ignore                                  = 0
	InitAudio                               = 0x00000010
	InitEvents                              = 0x00004000
	InitEverything                          = (InitTimer | InitAudio | InitVideo | InitEvents | InitJoystick | InitHaptic | InitGamecontroller)
	InitGamecontroller                      = 0x00002000
	InitHaptic                              = 0x00001000
	InitJoystick                            = 0x00000200
	InitNoparachute                         = 0x00100000
	InitTimer                               = 0x00000001
	InitVideo                               = 0x00000020
	InputLinuxev                            = 1
	InputLinuxkd                            = 1
	JoystickLinux                           = 1
	LilEndian                               = 1234
	LoadsoDlopen                            = 1
	MajorVersion                            = 2
	MaxLogMessage                           = 4096
	MinorVersion                            = 0
	MixMaxvolume                            = 128
	MutexMaxwait                            = (0)
	MutexTimedout                           = 1
	NullWhileLoopCondition                  = (0)
	Patchlevel                              = 1
	PowerLinux                              = 1
	Prealloc                                = 0x00000001
	Pressed                                 = 1
	Query                                   = -1
	Released                                = 0
	Rleaccel                                = 0x00000002
	RwopsJnifile                            = 3
	RwopsMemory                             = 4
	RwopsMemoryRo                           = 5
	RwopsStdfile                            = 2
	RwopsUnknown                            = 0
	RwopsWinfile                            = 1
	Swsurface                               = 0
	TexteditingeventTextSize                = (32)
	TextinputeventTextSize                  = (32)
	ThreadPthread                           = 1
	ThreadPthreadRecursiveMutex             = 1
	TimerUnix                               = 1
	TouchMouseid                            = (-1)
	VideoDriverDummy                        = 1
	VideoDriverX11                          = 1
	VideoDriverX11ConstParamXextadddisplay  = 1
	VideoDriverX11Dynamic                   = "LibX11.So.6"
	VideoDriverX11DynamicXcursor            = "LibXcursor.So.1"
	VideoDriverX11DynamicXext               = "LibXext.So.6"
	VideoDriverX11DynamicXinerama           = "LibXinerama.So.1"
	VideoDriverX11DynamicXinput2            = "LibXi.So.6"
	VideoDriverX11DynamicXrandr             = "LibXrandr.So.2"
	VideoDriverX11DynamicXss                = "LibXss.So.1"
	VideoDriverX11DynamicXvidmode           = "LibXxf86vm.So.1"
	VideoDriverX11HasXkbkeycodetokeysym     = 1
	VideoDriverX11SupportsGenericEvents     = 1
	VideoDriverX11Xcursor                   = 1
	VideoDriverX11Xinerama                  = 1
	VideoDriverX11Xinput2                   = 1
	VideoDriverX11Xinput2SupportsMultitouch = 1
	VideoDriverX11Xrandr                    = 1
	VideoDriverX11Xscrnsaver                = 1
	VideoDriverX11Xshape                    = 1
	VideoDriverX11Xvidmode                  = 1
	VideoOpengl                             = 1
	VideoOpenglGlx                          = 1
	VideoRenderOgl                          = 1
	WindowposCentered                       = (0)
	WindowposCenteredMask                   = 0x2FFF0000
	WindowposUndefined                      = (0)
	WindowposUndefinedMask                  = 0x1FFF0000
)
